<a href="https://colab.research.google.com/github/RyanTokManMokMTM/Tensorflow/blob/master/Tensorflow(logistic_regression_with_mnist(categorical_crossentropy_vs_sparse_categorical_crossentropy(One_Hot))).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import tensorflow as tf

In [2]:
(train_image,train_lable),(test_image,test_lable) =tf.keras.datasets.fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [7]:
train_image.shape

(60000, 28, 28)

In [9]:
train_lable.shape

(60000,)

In [15]:
model = tf.keras.Sequential()

In [16]:
model.add(tf.keras.layers.Flatten(input_shape=(28,28)))
model.add(tf.keras.layers.Dense(units=128,activation="relu"))
model.add(tf.keras.layers.Dense(units=10,activation="softmax"))

In [17]:
model.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=["acc"])

In [18]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 128)               100480    
_________________________________________________________________
dense_3 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [19]:
train_image =train_image/255
test_image = test_image/255

In [20]:
model.fit(train_image,train_lable,epochs=10)

Epoch 1/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.4928 - acc: 0.8259
Epoch 2/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3743 - acc: 0.8644
Epoch 3/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3341 - acc: 0.8779
Epoch 4/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3123 - acc: 0.8850
Epoch 5/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2948 - acc: 0.8901
Epoch 6/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2791 - acc: 0.8963
Epoch 7/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2678 - acc: 0.8995
Epoch 8/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2565 - acc: 0.9046
Epoch 9/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2464 - acc: 0.9077
Epoch 10/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2373 - acc: 0.9108


In [22]:
model.evaluate(test_image,test_lable)

313/313 [==============================] - 0s 1ms/step - loss: 0.3401 - acc: 0.8823


[0.34012702107429504, 0.8823000192642212]

**ONE HOT DATA: **

Suppose data is between 0-5
Normal : 0,1,2,3,4,5

Change that format to One How
==>

0 = [0,0,0,0,0]

1 = [1,0,0,0,0]

2 = [0,1,0,0,0]

3 = [0,0,1,0,0]

4 = [0,0,0,1,0]

5 = [0,0,0,0,1]

In [25]:
#Change to One hot
Train_lable_One_Hot = tf.keras.utils.to_categorical(train_lable)

In [27]:
Train_lable_One_Hot #One Hot

array([[0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [28]:
train_lable# Normal

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [31]:
Test_lable_One_Hot = tf.keras.utils.to_categorical(test_lable)

In [32]:
Test_lable_One_Hot

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [33]:
test_lable

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [34]:
#Example 
Test_lable_One_Hot.shape 
#10000 *[10] each list is included 10th number which's between 0 and 10

(10000, 10)

**Using One Hot Data To Train The Model**

In [36]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Flatten(input_shape=(28,28)))
model.add(tf.keras.layers.Dense(units=128,activation="relu"))
model.add(tf.keras.layers.Dense(units=10,activation="softmax"))

In [37]:
model.compile(optimizer="adam",
              loss = "categorical_crossentropy",
              metrics = ["acc"])

In [38]:
model.fit(train_image,Train_lable_One_Hot,epochs=10)

Epoch 1/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.4998 - acc: 0.8233
Epoch 2/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3758 - acc: 0.8641
Epoch 3/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3393 - acc: 0.8769
Epoch 4/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3124 - acc: 0.8848
Epoch 5/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2959 - acc: 0.8913
Epoch 6/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2815 - acc: 0.8966
Epoch 7/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2684 - acc: 0.9006
Epoch 8/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2570 - acc: 0.9040
Epoch 9/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2482 - acc: 0.9071
Epoch 10/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2393 - acc: 0.9103


In [42]:
predict = model.predict(test_image)

In [43]:
predict[0] # in this case the sum of the value in the list , the probabilty = 1

array([4.0825034e-07, 5.4833832e-10, 2.3099043e-08, 9.9809994e-10,
       2.9620525e-08, 3.0573509e-03, 3.9634770e-07, 8.4050260e-03,
       1.6355761e-08, 9.8853672e-01], dtype=float32)

In [44]:
np.argmax(predict[0]) # return indicate

9

In [45]:
np.max(predict[0]) #max number in list

0.9885367

In [46]:
test_lable[0]

9

conclusion：

If we using One Hot with activity as softmax

loss func = 'categorical_crossentropy'

if not
loss func = 'sparse_categorical_crossentropy'